ZIP_FILENAME = JamesChen.zip

clean:
	rm -rf $(ZIP_FILENAME)

zip-ps3b: clean
	zip -ur $(ZIP_FILENAME) ps3b

zip-ps4a: clean
	zip -ur $(ZIP_FILENAME) ps4a

zip-ps4b: clean
	zip -ur $(ZIP_FILENAME) ps4b

zip-ps5: clean
	zip -ur $(ZIP_FILENAME) ps5

zip-ps6: clean
	zip -ur $(ZIP_FILENAME) ps6

zip-ps7: clean
	zip -ur $(ZIP_FILENAME) ps7