ZIP_FILENAME = JamesChen.zip

zip-ps3b:
	rm -f $(ZIP_FILENAME) && zip -ur $(ZIP_FILENAME) ps3b

zip-ps4a:
	rm -f $(ZIP_FILENAME) && zip -ur $(ZIP_FILENAME) ps4a

zip-ps4b:
	rm -f $(ZIP_FILENAME) && zip -ur $(ZIP_FILENAME) ps4b